const LANGUAGE_MAP = [
    { name: 'Afrikaans', awsTranslateCode: 'af', flag: 'ZA' },
    { name: 'Albanian', awsTranslateCode: 'sq', flag: 'AL' },
    { name: 'Amharic', awsTranslateCode: 'am', flag: 'ET' },
    { name: 'Arabic', awsTranslateCode: 'ar', flag: 'SA' },
    { name: 'Armenian', awsTranslateCode: 'hy', flag: 'AM' },
    { name: 'Azerbaijani', awsTranslateCode: 'az', flag: 'AZ' },
    { name: 'Bengali', awsTranslateCode: 'bn', flag: 'BD' },
    { name: 'Bosnian', awsTranslateCode: 'bs', flag: 'BA' },
    { name: 'Bulgarian', awsTranslateCode: 'bg', flag: 'BG' },
    { name: 'Catalan', awsTranslateCode: 'ca', flag: 'ES' },
    { name: 'Chinese (Simplified)', awsTranslateCode: 'zh', flag: 'CN' },
    { name: 'Chinese (Traditional)', awsTranslateCode: 'zh-TW', flag: 'TW' },
    { name: 'Croatian', awsTranslateCode: 'hr', flag: 'HR' },
    { name: 'Czech', awsTranslateCode: 'cs', flag: 'CZ' },
    { name: 'Danish', awsTranslateCode: 'da', flag: 'DK' },
    { name: 'Dari', awsTranslateCode: 'fa-AF', flag: 'AF' },
    { name: 'Dutch', awsTranslateCode: 'nl', flag: 'NL' },
    { name: 'English', awsTranslateCode: 'en', flag: 'GB' },
    { name: 'Estonian', awsTranslateCode: 'et', flag: 'EE' },
    { name: 'Farsi (Persian)', awsTranslateCode: 'fa', flag: 'IR' },
    { name: 'Filipino, Tagalog', awsTranslateCode: 'tl', flag: 'PH' },
    { name: 'Finnish', awsTranslateCode: 'fi', flag: 'FI' },
    { name: 'French', awsTranslateCode: 'fr', flag: 'FR' },
    { name: 'French (Canada)', awsTranslateCode: 'fr-CA', flag: 'CA' },
    { name: 'Georgian', awsTranslateCode: 'ka', flag: 'GE' },
    { name: 'German', awsTranslateCode: 'de', flag: 'DE' },
    { name: 'Greek', awsTranslateCode: 'el', flag: 'GR' },
    { name: 'Gujarati', awsTranslateCode: 'gu', flag: 'IN' },
    { name: 'Haitian Creole', awsTranslateCode: 'ht', flag: 'HT' },
    { name: 'Hausa', awsTranslateCode: 'ha', flag: 'NG' },
    { name: 'Hebrew', awsTranslateCode: 'he', flag: 'IL' },
    { name: 'Hindi', awsTranslateCode: 'hi', flag: 'IN' },
    { name: 'Hungarian', awsTranslateCode: 'hu', flag: 'HU' },
    { name: 'Icelandic', awsTranslateCode: 'is', flag: 'IS' },
    { name: 'Indonesian', awsTranslateCode: 'id', flag: 'ID' },
    { name: 'Irish', awsTranslateCode: 'ga', flag: 'IE' },
    { name: 'Italian', awsTranslateCode: 'it', flag: 'IT' },
    { name: 'Japanese', awsTranslateCode: 'ja', flag: 'JP' },
    { name: 'Kannada', awsTranslateCode: 'kn', flag: 'IN' },
    { name: 'Kazakh', awsTranslateCode: 'kk', flag: 'KZ' },
    { name: 'Korean', awsTranslateCode: 'ko', flag: 'KR' },
    { name: 'Latvian', awsTranslateCode: 'lv', flag: 'LV' },
    { name: 'Lithuanian', awsTranslateCode: 'lt', flag: 'LT' },
    { name: 'Macedonian', awsTranslateCode: 'mk', flag: 'MK' },
    { name: 'Malay', awsTranslateCode: 'ms', flag: 'MY' },
    { name: 'Malayalam', awsTranslateCode: 'ml', flag: 'IN' },
    { name: 'Maltese', awsTranslateCode: 'mt', flag: 'MT' },
    { name: 'Marathi', awsTranslateCode: 'mr', flag: 'IN' },
    { name: 'Mongolian', awsTranslateCode: 'mn', flag: 'MN' },
    { name: 'Norwegian (Bokmål)', awsTranslateCode: 'no', flag: 'NO' },
    { name: 'Pashto', awsTranslateCode: 'ps', flag: 'AF' },
    { name: 'Polish', awsTranslateCode: 'pl', flag: 'PL' },
    { name: 'Portuguese (Brazil)', awsTranslateCode: 'pt', flag: 'BR' },
    { name: 'Portuguese (Portugal)', awsTranslateCode: 'pt-PT', flag: 'PT' },
    { name: 'Punjabi', awsTranslateCode: 'pa', flag: 'IN' },
    { name: 'Romanian', awsTranslateCode: 'ro', flag: 'RO' },
    { name: 'Russian', awsTranslateCode: 'ru', flag: 'RU' },
    { name: 'Serbian', awsTranslateCode: 'sr', flag: 'RS' },
    { name: 'Sinhala', awsTranslateCode: 'si', flag: 'LK' },
    { name: 'Slovak', awsTranslateCode: 'sk', flag: 'SK' },
    { name: 'Slovenian', awsTranslateCode: 'sl', flag: 'SI' },
    { name: 'Somali', awsTranslateCode: 'so', flag: 'SO' },
    { name: 'Spanish', awsTranslateCode: 'es', flag: 'ES' },
    { name: 'Spanish (Mexico)', awsTranslateCode: 'es-MX', flag: 'MX' },
    { name: 'Swahili', awsTranslateCode: 'sw', flag: 'TZ' },
    { name: 'Swedish', awsTranslateCode: 'sv', flag: 'SE' },
    { name: 'Tamil', awsTranslateCode: 'ta', flag: 'IN' },
    { name: 'Telugu', awsTranslateCode: 'te', flag: 'IN' },
    { name: 'Thai', awsTranslateCode: 'th', flag: 'TH' },
    { name: 'Turkish', awsTranslateCode: 'tr', flag: 'TR' },
    { name: 'Ukrainian', awsTranslateCode: 'uk', flag: 'UA' },
    { name: 'Urdu', awsTranslateCode: 'ur', flag: 'PK' },
    { name: 'Uzbek', awsTranslateCode: 'uz', flag: 'UZ' },
    { name: 'Vietnamese', awsTranslateCode: 'vi', flag: 'VN' },
    { name: 'Welsh', awsTranslateCode: 'cy', flag: 'GB' }
] as const;